#ifndef SNAPSHOT_SUBSYSTEMS_H
#define SNAPSHOT_SUBSYSTEMS_H

/*
 * Per-subsystem snapshot save/load entry points.
 *
 * Each emulated subsystem owns a `*_save_state` writer and a
 * `*_load_state` reader. The save side appends a single tagged chunk
 * to a snapshot writer; the load side decodes a single chunk's payload
 * on top of an already-initialised subsystem (i.e. arc_init() has run
 * and any timers are already registered with `timer_add()`). The
 * orchestrator dispatches to `*_load_state` based on the chunk's
 * FourCC ID. Per-chunk versioning lets one subsystem change its
 * on-disk shape without forcing every other subsystem to rev too.
 *
 * Conventions:
 *   - Save functions return 1 on success, 0 on writer failure (OOM, etc.)
 *   - Load functions return 1 on success, 0 on truncated/invalid payload
 *   - Load functions take the chunk version so they can opt into a
 *     forward/backward-compatible decode if/when fields are added
 *   - Embedded `emu_timer_t` state is restored via `timer_restore()`
 *     (declared in src/timer.h) so the global linked list stays sorted
 */

#include <stddef.h>
#include <stdint.h>

#include "snapshot.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ARM core (src/arm.c) */
int arm_save_state(snapshot_writer_t *w);
int arm_load_state(snapshot_payload_reader_t *r, uint32_t version);

/* CP15 / ARM3 cache controller (src/cp15.c). Only emitted/loaded when
 * arm_has_cp15 is set. */
int cp15_save_state(snapshot_writer_t *w);
int cp15_load_state(snapshot_payload_reader_t *r, uint32_t version);

/* Floating-point accelerator (src/fpa.c). Only emitted when fpaena. */
int fpa_save_state(snapshot_writer_t *w);
int fpa_load_state(snapshot_payload_reader_t *r, uint32_t version);

/* RAM contents and the memstat / mempoint page tables (src/mem.c).
 * Note that mempoint is saved as offsets from the ram base so it
 * survives a fresh ram allocation on the load side. */
int mem_save_state(snapshot_writer_t *w);
int mem_load_state(snapshot_payload_reader_t *r, uint32_t version);

/* MEMC1/1a state (src/memc.c) including the CAM, page mappings,
 * DMA pointers and timestamps. */
int memc_save_state(snapshot_writer_t *w);
int memc_load_state(snapshot_payload_reader_t *r, uint32_t version);

/* IOC chip and its 4 timers (src/ioc.c). */
int ioc_save_state(snapshot_writer_t *w);
int ioc_load_state(snapshot_payload_reader_t *r, uint32_t version);

/* VIDC10 video controller (src/vidc.c). Includes the register cache,
 * timing/DMA state, and the line timer. The palette lookup arrays
 * (vidc.pal / vidc.pal8 / vidlookup) are derived state and are
 * regenerated by vidc_redopalette() during the load. */
int vidc_save_state(snapshot_writer_t *w);
int vidc_load_state(snapshot_payload_reader_t *r, uint32_t version);

/* Keyboard / mouse I2C state machine (src/keyboard.c). Host-input
 * mirror state is reset on load (the host-side input is platform
 * state, not emulator state). */
int keyboard_save_state(snapshot_writer_t *w);
int keyboard_load_state(snapshot_payload_reader_t *r, uint32_t version);

/* CMOS RAM, RTC and I2C state machine (src/cmos.c). Wall-clock RTC
 * bytes are intentionally NOT serialised — they will be refreshed by
 * the next cmos_tick() callback. */
int cmos_save_state(snapshot_writer_t *w);
int cmos_load_state(snapshot_payload_reader_t *r, uint32_t version);

/* DS2401 1-wire ID ROM state machine (src/ds2401.c). */
int ds2401_save_state(snapshot_writer_t *w);
int ds2401_load_state(snapshot_payload_reader_t *r, uint32_t version);

/* Sound subsystem (src/sound.c). Period/enable/gain/filter plus the
 * in-flight sample buffer pointers. The IIR filter history lives
 * inside function-local statics in sound.c, so the helper accesses
 * them via private save/load callbacks declared there. */
int sound_save_state(snapshot_writer_t *w);
int sound_load_state(snapshot_payload_reader_t *r, uint32_t version);

/* IOEB (used by IOEB-equipped machines, src/ioeb.c). */
int ioeb_save_state(snapshot_writer_t *w);
int ioeb_load_state(snapshot_payload_reader_t *r, uint32_t version);

/* A4 LC controller (src/lc.c). Only emitted on MACHINE_TYPE_A4. */
int lc_save_state(snapshot_writer_t *w);
int lc_load_state(snapshot_payload_reader_t *r, uint32_t version);

/* WD1770 floppy controller (src/wd1770.c). Skipped if fdctype == FDC_82C711. */
int wd1770_save_state(snapshot_writer_t *w);
int wd1770_load_state(snapshot_payload_reader_t *r, uint32_t version);

/* 82C711 SuperIO floppy controller (src/82c711_fdc.c). Skipped unless
 * fdctype == FDC_82C711. Only the static `_fdc` instance is serialised;
 * podule overrides allocate their own copies and aren't snapshotted. */
int c82c711_fdc_save_state(snapshot_writer_t *w);
int c82c711_fdc_load_state(snapshot_payload_reader_t *r, uint32_t version);

/* Disc-layer globals (src/disc.c): motor, current track per drive,
 * write-protect flags, etc. ADF/HFE in-memory track buffers are NOT
 * serialised — they get repopulated by replaying disc_seek() to the
 * restored disc_current_track[drive] after load. */
int disc_save_state(snapshot_writer_t *w);
int disc_load_state(snapshot_payload_reader_t *r, uint32_t version);

/* IDE hard disc controller (src/ide.c). Only emitted when
 * fdctype == FDC_82C711 and an HD image is configured. The file
 * handles and IRQ callbacks are re-established by c82c711_init()
 * during arc_init() before the snapshot state is applied. */
int ide_internal_save_state(snapshot_writer_t *w);
int ide_internal_load_state(snapshot_payload_reader_t *r, uint32_t version);

#ifdef __cplusplus
}
#endif

#endif /* SNAPSHOT_SUBSYSTEMS_H */
